// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfuh9mmre82R46eOUmUGipi1D74BiY6yI',
    appId: '1:409015429474:web:775849ba6e69aafcc6a43b',
    messagingSenderId: '409015429474',
    projectId: 'anis-437c3',
    authDomain: 'anis-437c3.firebaseapp.com',
    storageBucket: 'anis-437c3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfuh9mmre82R46eOUmUGipi1D74BiY6yI',
    appId: '1:409015429474:android:4661d9c3048e38b6c6a43b',
    messagingSenderId: '409015429474',
    projectId: 'anis-437c3',
    storageBucket: 'anis-437c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfuh9mmre82R46eOUmUGipi1D74BiY6yI',
    appId: '1:409015429474:ios:775849ba6e69aafcc6a43b',
    messagingSenderId: '409015429474',
    projectId: 'anis-437c3',
    authDomain: 'anis-437c3.firebaseapp.com',
    storageBucket: 'anis-437c3.firebasestorage.app',
    iosBundleId: 'com.aniskhatamat.app',
  );
}
